steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/q-torial-api', '-f', './Dockerfile', '.']
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/q-torial-api']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'q-torial-api',
           '--image', 'gcr.io/$PROJECT_ID/q-torial-api',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--set-env-vars', 'PROJECT_ID=${_PROJECT_ID}',
           '--service-account', '${_SERVICE_ACCOUNT}',
           '--allow-unauthenticated',
           '--quiet'
    ]
images:
  - gcr.io/$PROJECT_ID/q-torial-api








